project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!ignored-dir/"

execute:
  freeze: auto  # Re-render only when source changes

website:
#   google-analytics:
#     tracking-id: "G-W9H0V3N3EJ"
#     anonymize-ip: true
  # cookie-consent:
  #   type: implied
  #   style: simple
  #   palette: light
  #   language: en
  title: "Tais"
  description: "Website of Tais company"
  site-url: "https://taisnet.com"
  repo-url: "https://github.com/TCPSnet/taisnet"
#  repo-actions: [edit, issue]
  favicon: images/net2.png
  search: false # no magnifier on navbar
  announcement:
    icon: cone-striped
    dismissable: true
    content: "Website under construction"
    type: warning
    position: below-navbar
  page-footer:
    left: |
      {{< fa regular copyright >}} Copyright 2025, Davide Rossetti
    # right: |
    #   Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/) <br>
#      [Code at {{< fa brands github >}} GitHub]({{< var websites.gh_repo >}})

  navbar:
    logo: images/TAIS.png

    right:
      - href: index.qmd
        icon: house-door-fill
        text: " "
      # - href: index.qmd
      #   icon: house-door-fill
      #   text: "Home"
      - href: network/index.qmd
        icon: tools
        text: "Prodotti"
      # - href: services.qmd
      #   icon: people-fill
      #   text: "Servizi"
      # # - href: news.qmd
      # #   text: "News"

format:
  html:
    toc: true
    toc-location: "left"
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    fontsize: 1em
    theme: theme/davides_theme.scss
    # css: theme/styles.css
    ##----- code highlighting style
    highlight-style: monokai # atom-one # github # dracula
    mainfont: "Lato"
    monofont: "Fira Mono"
    ## ----- custom cookie consent linked to Google Analytics
    include-after-body: theme/custom-cookie.html


