---
title: "_Share experience for common growth_"
#subtitle: "..."
title-block-banner: "#5EBEE7"
title-block-banner-color: body
toc: false
format: html
  # html: 
  #   page-layout: full
freeze: true
---

<!-- https://quarto.org/docs/output-formats/page-layout.html -->
<!-- > [*Website under construction...*]{style="color:#A14155; font-size: 1.5em;"} -->

<!-- https://www.paolopenzo.it/area-temporary-management/ -->

<!-- Propongo collaborazioni a progetto, affiancando team interni, condividendo iniziative e trasferendo nel contempo competenze, senza interruzione o stravolgimenti della normale operatività. Specificamente, posso offrire supporto in: -->

<!-- + aerea vendite, incluso nel consolidamento della rete di partner strategici. -->
<!-- + esplorazione di nuovi mercati, in Italia e all'estero -->
<!-- + gestione delle attività di immissione di un nuovo prodotto o servizio -->
<!-- + area acquisti, con consulenza nella ricerca fornitori -->

<!-- Negli ultimi 25 anni, ho acquisito esperienze nei settori di applicazione dei tessuti tecnici (classificazione Techtextil). Provengo dal mondo della pesca (professionale e sportiva), dell’acquacoltura e della nautica (diporto e cantieristica). -->

## Temporary Sales Manager

Valuto con interesse incarichi temporanei o collaborazioni su progetti mirati, con cui affiancare i team in modo da fornire un supporto operativo in piena continuità operativa e rispetto delle dinamiche aziendali già attive.

Posso contribuire nell'ambito di:

+ **sviluppo commerciale**, incluso il consolidamento di reti strategiche di partner  
+ **apertura di nuovi mercati**, in Italia e all’estero  
+ **gestione** del lancio di prodotti o servizi  
+ **processi di approvvigionamento**, dalla ricerca alla valutazione dei fornitori  

Con 25 anni di esperienza in numerose applicazioni nel campo dei tessuti tecnici (classificazione Techtextil), porto una competenza consolidata nei settori della pesca (sportiva e professionale), dell’acquacoltura e della nautica (diporto e cantieristica).

Sono aperto a collaborare con realtà che valorizzino esperienza, flessibilità e un approccio pragmatico all’innovazione.

<br>
<!-- [Email me](mailto:rossettidav@gmail.com){.theme-button} -->
<a href="mailto:rossettidav@gmail.com" class="theme-button"><i class="fas fa-envelope"></i>&nbsp;&nbsp;&nbsp;Email me</a>
 
 
 
 
 <!-- ## Sales & Marketing Management -->

<!-- xxxxxxxx -->
